# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install coveralls
  - pip install -r requirements_dev.txt
  - python setup.py install

script: pytest -v -s

after_success:
  coveralls
