# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: required
dist: trusty

language: python

python:
  - "3.5"
  - "3.6"

services:
  - docker

before_install:
  - docker pull busybox
  - docker pull quay.io/biocontainers/snakemake:4.3.1--py36_0

install:
  - pip install coveralls
  - pip install -r requirements_dev.txt
  - python setup.py install

script: pytest -v -s

after_success:
  coveralls
